package com.lifeforge.os.presentation.localization

data class L10n(
    val appName: String,
    val home: String,
    val settings: String,
    val onboarding: String,
    val continueLabel: String,
    val greeting: String,
    val waterToday: String,
    val waterGoal: String,
    val addWater: String,
    val activeHabits: String,
    val openTasks: String,
    val noTasks: String,
    val profileTitle: String,
    val nameLabel: String,
    val waterGoalLabel: String,
    val caloriesGoalLabel: String,
    val unitsLabel: String,
    val unitsMetric: String,
    val unitsImperial: String,
    val themeModeLabel: String,
    val themeLight: String,
    val themeDark: String,
    val themeSystem: String,
    val themePresetLabel: String,
    val notificationsLabel: String,
    val languageLabel: String,
    val english: String,
    val arabic: String,
    val loading: String,
    val errorGeneric: String,
    val enteredNameRequired: String,
    val habits: String,
    val noHabits: String,
    val addHabit: String,
    val habitNameHint: String,
    val delete: String,
    val tasks: String,
    val addTask: String,
    val taskTitleHint: String,
    val nutrition: String,
    val gym: String,
    val journal: String,
    val recovery: String,
    val timers: String,
    val goals: String,
    val routines: String,
    val notes: String,
    val books: String,
    val courses: String,
    val entertainment: String,
    val back: String,
    val add: String,
    val title: String,
    val calories: String,
    val protein: String,
    val carbs: String,
    val fat: String,
    val remaining: String,
    val quickAddWater: String,
    val search: String,
    val noResults: String,
    val today: String,
    val streak: String,
    val relapse: String,
    val streakLabel: String,
    val dayLabel: String,
    val addRelapseEntry: String,
    val addRegularEntry: String,
    val relapseTrigger: String,
    val whatHappened: String,
    val entries: String,
    val noEntries: String,
    val start: String,
    val stop: String,
    val reset: String,
    val minutes: String,
    val seconds: String,
    val addTimer: String,
    val noTimers: String,
    val progress: String,
    val addGoal: String,
    val goalTarget: String,
    val noGoals: String,
    val addRoutine: String,
    val noRoutines: String,
    val noItems: String,
    val completed: String,
    val addNote: String,
    val noNotes: String,
    val noteContentHint: String,
    val addBook: String,
    val bookTitle: String,
    val bookAuthor: String,
    val noBooks: String,
    val statusLabel: String,
    val addCourse: String,
    val courseTitle: String,
    val courseProvider: String,
    val noCourses: String,
    val addItem: String,
    val mediaTitle: String,
    val noMedia: String,
    val recentSessionsLabel: String,
    val favorites: String,
    val featuresLabel: String,
)

object LocalizedStrings {
    fun stringsFor(language: String): L10n =
        if (language == "ar") ar else en

    val en = L10n(
        appName = "LifeForge OS",
        home = "Home",
        settings = "Settings",
        onboarding = "Welcome",
        continueLabel = "Get Started",
        greeting = "Hi",
        waterToday = "Water today",
        waterGoal = "Daily goal",
        addWater = "Add water",
        activeHabits = "Active habits",
        openTasks = "Open tasks",
        noTasks = "No open tasks",
        profileTitle = "Your profile",
        nameLabel = "Name",
        waterGoalLabel = "Daily water goal (ml)",
        caloriesGoalLabel = "Daily calorie goal",
        unitsLabel = "Units",
        unitsMetric = "Metric",
        unitsImperial = "Imperial",
        themeModeLabel = "Theme mode",
        themeLight = "Light",
        themeDark = "Dark",
        themeSystem = "System",
        themePresetLabel = "Theme preset",
        notificationsLabel = "Notifications",
        languageLabel = "Language",
        english = "English",
        arabic = "العربية",
        loading = "Loading…",
        errorGeneric = "Something went wrong",
        enteredNameRequired = "Please enter your name",
        habits = "Habits",
        noHabits = "No habits yet",
        addHabit = "Add habit",
        habitNameHint = "Habit name",
        delete = "Delete",
        tasks = "Tasks",
        addTask = "Add task",
        taskTitleHint = "Task title",
        nutrition = "Nutrition",
        gym = "Gym",
        journal = "Journal",
        recovery = "Recovery",
        timers = "Timers",
        goals = "Goals",
        routines = "Routines",
        notes = "Notes",
        books = "Books",
        courses = "Courses",
        entertainment = "Entertainment",
        back = "Back",
        add = "Add",
        title = "Title",
        calories = "Calories",
        protein = "Protein",
        carbs = "Carbs",
        fat = "Fat",
        remaining = "remaining",
        quickAddWater = "+250 ml",
        search = "Search",
        noResults = "No results",
        today = "Today",
        streak = "Streak",
        relapse = "Relapse",
        streakLabel = "Streak",
        dayLabel = "days",
        addRelapseEntry = "Add relapse entry",
        addRegularEntry = "Add today's entry",
        relapseTrigger = "Trigger",
        whatHappened = "What happened",
        entries = "Entries",
        noEntries = "No journal entries yet",
        start = "Start",
        stop = "Stop",
        reset = "Reset",
        minutes = "min",
        seconds = "sec",
        addTimer = "Add timer",
        noTimers = "No timers",
        progress = "Progress",
        addGoal = "Add goal",
        goalTarget = "Target",
        noGoals = "No goals",
        addRoutine = "Add routine",
        noRoutines = "No routines",
        noItems = "No items",
        completed = "Completed",
        addNote = "Add note",
        noNotes = "No notes",
        noteContentHint = "Write a note…",
        addBook = "Add book",
        bookTitle = "Book title",
        bookAuthor = "Author",
        noBooks = "No books",
        statusLabel = "Status",
        addCourse = "Add course",
        courseTitle = "Course title",
        courseProvider = "Provider",
        noCourses = "No courses",
        addItem = "Add",
        mediaTitle = "Title",
        noMedia = "Nothing here yet",
        recentSessionsLabel = "Completed sessions",
        favorites = "Favorites",
        featuresLabel = "Features",
    )

    val ar = L10n(
        appName = "لايف فورج أو إس",
        home = "الرئيسية",
        settings = "الإعدادات",
        onboarding = "مرحباً بك",
        continueLabel = "ابدأ الآن",
        greeting = "مرحباً",
        waterToday = "الماء اليوم",
        waterGoal = "الهدف اليومي",
        addWater = "إضافة ماء",
        activeHabits = "العادات النشطة",
        openTasks = "المهام المفتوحة",
        noTasks = "لا توجد مهام مفتوحة",
        profileTitle = "ملفك الشخصي",
        nameLabel = "الاسم",
        waterGoalLabel = "الهدف اليومي للماء (مل)",
        caloriesGoalLabel = "هدف السعرات اليومي",
        unitsLabel = "الوحدات",
        unitsMetric = "المترية",
        unitsImperial = "الإمبراطورية",
        themeModeLabel = "وضع المظهر",
        themeLight = "فاتح",
        themeDark = "داكن",
        themeSystem = "النظام",
        themePresetLabel = "النمط اللوني",
        notificationsLabel = "الإشعارات",
        languageLabel = "اللغة",
        english = "English",
        arabic = "العربية",
        loading = "جارٍ التحميل…",
        errorGeneric = "حدث خطأ",
        enteredNameRequired = "يرجى إدخال اسمك",
        habits = "العادات",
        noHabits = "لا توجد عادات بعد",
        addHabit = "إضافة عادة",
        habitNameHint = "اسم العادة",
        delete = "حذف",
        tasks = "المهام",
        addTask = "إضافة مهمة",
        taskTitleHint = "عنوان المهمة",
        nutrition = "التغذية",
        gym = "الرياضة",
        journal = "اليوميات",
        recovery = "التعافي",
        timers = "المؤقتات",
        goals = "الأهداف",
        routines = "الروتين",
        notes = "الملاحظات",
        books = "الكتب",
        courses = "الدورات",
        entertainment = "الترفيه",
        back = "رجوع",
        add = "إضافة",
        title = "العنوان",
        calories = "السعرات",
        protein = "البروتين",
        carbs = "الكربوهيدرات",
        fat = "الدهون",
        remaining = "متبقي",
        quickAddWater = "+250 مل",
        search = "بحث",
        noResults = "لا نتائج",
        today = "اليوم",
        streak = "التسلسل",
        relapse = "انتكاسة",
        streakLabel = "التسلسل",
        dayLabel = "أيام",
        addRelapseEntry = "إضافة تسجيل انتكاسة",
        addRegularEntry = "إضافة تسجيل اليوم",
        relapseTrigger = "المحفز",
        whatHappened = "ماذا حدث",
        entries = "التسجيلات",
        noEntries = "لا توجد تسجيلات بعد",
        start = "بدء",
        stop = "إيقاف",
        reset = "تصفير",
        minutes = "دقيقة",
        seconds = "ثانية",
        addTimer = "إضافة مؤقت",
        noTimers = "لا توجد مؤقتات",
        progress = "التقدم",
        addGoal = "إضافة هدف",
        goalTarget = "الهدف",
        noGoals = "لا توجد أهداف",
        addRoutine = "إضافة روتين",
        noRoutines = "لا توجد روتينات",
        noItems = "لا عناصر",
        completed = "مكتمل",
        addNote = "إضافة ملاحظة",
        noNotes = "لا توجد ملاحظات",
        noteContentHint = "اكتب ملاحظة…",
        addBook = "إضافة كتاب",
        bookTitle = "عنوان الكتاب",
        bookAuthor = "المؤلف",
        noBooks = "لا توجد كتب",
        statusLabel = "الحالة",
        addCourse = "إضافة دورة",
        courseTitle = "عنوان الدورة",
        courseProvider = "الجهة",
        noCourses = "لا توجد دورات",
        addItem = "إضافة",
        mediaTitle = "العنوان",
        noMedia = "لا شيء هنا بعد",
        recentSessionsLabel = "الجلسات المكتملة",
        favorites = "المفضلة",
        featuresLabel = "المميزات",
    )
}